### ISSUE TITLE
feedback #1

### ISSUE THREAD

**Issue by rodneyrehm** [varemenos/sass.js-playground#1]
nice work! this is ace thing turned out much nicer than anticipated :)
1. I think "demoting" the SourceMaps into their own panel (like Options, Filesystem - hidden by default) is ok, since this is not A-grade information.
2. when I put together the options block, I thought I'd visualize it like it was JSON with editable values. I don't think this was a very good idea to begin with. In this context it looks confusing…
3. It is possible that the tabs at the top left are not obvious enough
4. that note "this fun was had" should not go in the head, in fact I don't need it in there at all. If anyone's name should go anywhere on that page, it's your's.
5. when two or three panels are shown, input/output may be better shown in a single colum?

again, cool stuff!

**Comment by varemenos** [comment]
Ok, so I finally found some free time this week and I've worked through 1, 2 and 4

3 and 5 require a little more attention, so I will probably work on them tomorrow (my mind will be in a better state than it is now)

**Comment by rodneyrehm** [comment]
nice!

**Comment by varemenos** [comment]
I've worked on 3 a bit but I got kinda distracted and ended up in a different result :stuck_out_tongue: 
I will try find some free time in Tuesday to work on it a little more

**Comment by rodneyrehm** [comment]
hehe, no rush :)

I'm still tinkering with some of the new APIs… just landed some sort of importer API so you can intercept file loading. we'll see when/if I get to custom functions…

**Comment by varemenos** [comment]
Apart from some icon changes I think the design is ready, what do you think?

**Comment by rodneyrehm** [comment]
very nice! 

I think the "delete file" in filesystem should `confirm()` the action.

I'm wondering if I should release sass.js `0.7.0-beta.1` so you could properly import it using bower/npm, what do you think?

> For more information on how to convert SCSS and SASS in the browser using emscripted & libsass see the Sass.js repository. 

»Sass.js v0.7.0-beta.1 provding libsass v3.2.0-beta.5 via emscripten v1.2.3« would be concise and more detailed, don't you think? I'd have to expose the versions of libsass and emscripten somehow - any ideas where to store them so you can easily import that info into the HTML? Or is it sufficient to have this stored on `Sass.version`, `Sass.libsassVersion`, `Sass.emscriptenVersion` right on the object?

**Comment by varemenos** [comment]
> I think the "delete file" in filesystem should confirm() the action.

That makes sense, I will create a new issue for it.

> I'm wondering if I should release sass.js 0.7.0-beta.1 so you could properly import it using bower/npm, what do you think?

Ya it would be ideal to load them via bower or npm but I'd suggest you to wait until you feel it's ready, so don't rush yourself.

> any ideas where to store them so you can easily import that info into the HTML? Or is it sufficient to have this stored on Sass.version, Sass.libsassVersion, Sass.emscriptenVersion right on the object?

I'd go for something like this:

``` js
console.log(Sass.version);
> 3.2
```

``` js
console.log(Sass.libs);
> {
  sass: Sass.version,
  libsass: libsass.version,
  emscripten: emscripten.version
}
```

**Comment by rodneyrehm** [comment]
will look into it. won't get to it before sat/sun, tho.

**Comment by varemenos** [comment]
I'm going to close this issue for now if you don't mind.

**Comment by rodneyrehm** [comment]
don't mind at all
