### ISSUE TITLE
redesign

### ISSUE THREAD

**Issue by varemenos** [varemenos/sass.js-playground#7]
We should really work on the header.
We could pack some useful details in there about the project and possibly make it way more attractive in the process. Thoughts?

should we consider making a SASS.js logo?
## Update

subtasks:
- [x] redesign the header, the options and filesystem panel
- [x] make the editors takes as much space as their parents can provide
- [x] make the CSS editor (the output) read only
- [x] [custom error highlighting for stdin](http://i.imgur.com/Et4OVXx.jpg)
- [x] [custom error highlighting for filesystem](http://i.imgur.com/Gb8akm6.png) (on errors originated from the filesystem, open the filesystem ]tab, open the erroneous file in the filesystem editor and highlight the error)
- [x] remove edit buttons in filesystem, clicking on a file's block triggers the edit action
- [x] clean up messy parts of the codebase (modularize it with webpack)
- [x] prepare something better for the text below the header (descriptions, links, call for contribution etc)

**Comment by rodneyrehm** [comment]
Have at it if you think there's something to improve. I'm not able to spend too much time on this at the moment.

**Comment by varemenos** [comment]
Ok great, I'm gonna try to get something ready little after x-mas.
About the logo, I will contact a designer friend of mine and see if he is interested in preparing a sample logo which we can then evaluate on whether it fits the project and whether we should use it.

edit: I've changed the title into a less specific one, since I will rework various parts of the playground (not just the header). I've also added some sub tasks for this issue.

**Comment by varemenos** [comment]
I've changed title into a less specific one, since I will rework on various "visual stuff" of the playground (not only the header)

**Comment by varemenos** [comment]
I've pushed many changes for this project in the redesign branch (you could check the checklist above for an overview of what the changes are about), unfortunately the changelog won't be much of help (I will try to split it down into more meaningful commits later before submitting the PR). For now I would like your opinion on the changes.

There are only 2 things that I'd like to address before submitting the PR:
1. the logo whose mockup is still a W.I.P. (it's x-mas so it might take some time)
2. the text in the header & subheader, I've added 3 sample columns in there but they are not what I had in mind. I'd like to use the first column to display add a 2-3 lines worth of description for the main project (Sass.js), in the second one I'm not so sure atm (maybe contributions, credits etc?) and use the third one to have a paragraph about contributing to the project, github source and issue links etc.

**Comment by rodneyrehm** [comment]
Looks good! I think the second header row (with the three columns) is a bit much, though. I thought displaying the versions in the header was ok, but additional info should probably go into a footer?

**Comment by varemenos** [comment]
Hmmm, I don't know, I used the 2nd header cause I wanted to keep the information in one place. If we turned that into a footer we would have them spit in the top and bottom of the page. Do you want to keep it (either as subheader or footer)  and populate it with useful information or get rid of it?

**Comment by rodneyrehm** [comment]
I'd move any explanations (the text you added) to the footer. Those texts aren't a bad idea, but they shouldn't be part of the header.

**Comment by varemenos** [comment]
Alright I will see what I can do.
Do you think you could help out with the footer  text?
Or maybe we could remove the subheader for now and work on the footer and it's content in another PR

**Comment by rodneyrehm** [comment]
I don't think there's anything wrong with your texts… Maybe some more prose and you have the story of how things fit together:

> Sass.js is is a JavaScript API on top of libsass. Libsass is the C++ version of the Sass compiler (originally written in Ruby). It was built for performance and easy integration into all the tools. In order to run C++ in the browser it is converted to JavaScript by Emscripen. Emscripten is an LLVM-based compiler that converts C/C++ to highly optimized ASM.js.

**Comment by varemenos** [comment]
Yep, that's what I had in mind, use something like  that for the first column and utilize the other 2 for other purposes. 
The logo is blocking so while that's being worked I can focus on the final touches and the footer.

**Comment by varemenos** [comment]
Btw, http://medialize.github.io/playground.sass.js/ this is way too long. Is there something we could do about it?

**Comment by rodneyrehm** [comment]
what did you have in mind about the domain?

we could ask someone from the Sass org if they're interested in hosting the playground on their site. However, the last time I offered to transfer sass.js to them, they declined…

I'm fine with the URL as it is.

**Comment by varemenos** [comment]
We could change the repo's name to try.sass.js and end up with http://medialize.github.io/try.sass.js or somehow embed it to the sass.js repo (but obviously keeping it separate)

**Comment by varemenos** [comment]
There is also the option of js.org, we should try and get the sass.js.org subdomain from https://dns.js.org/

**Comment by rodneyrehm** [comment]
sounds good, do you want to set it up?

**Comment by varemenos** [comment]
Sure, I will give it a go

**Comment by varemenos** [comment]
And it's good to go :)
http://sass.js.org

Btw could you update the link of the repo to point to this url? I can change everything else but not that.

**Comment by rodneyrehm** [comment]
cool!

**Comment by varemenos** [comment]
Ohh I forgot to mention, we might have a little down time for a while due to DNS caching

**Comment by varemenos** [comment]
I ended up not implementing an action footer, I've moved that block in an "information" modal.

**Comment by varemenos** [comment]
Ok, seems like the logo will take a while and I really don't have the time for it.
I'll be joining the Greek army in a week to do my mandatory 9 month military service so we can probably skip the logo for now :(

**Comment by rodneyrehm** [comment]
> I'll be joining the Greek army in a week to do my mandatory 9 month military service …

woha. good luck!
